FROM williamyeh/wrk:4.0.2

# The workdir of the base image
WORKDIR /data

# https://stackoverflow.com/questions/48736212/bad-file-descriptor-error-during-apk-update-in-docker-container-why
RUN rm -rf /var/cache/apk &&\
    mkdir /var/cache/apk &&\
    apk add curl unzip gcc make alpine-sdk lua5.3 lua5.3-dev outils-md5 &&\
    wget https://luarocks.org/releases/luarocks-3.0.4.tar.gz &&\
    tar zxpf luarocks-3.0.4.tar.gz &&\
    cd luarocks-3.0.4 &&\
    ./configure  &&\
# https://github.com/luarocks/luarocks/issues/901
    export USER=root &&\
    make bootstrap &&\
    luarocks install luasocket &&\
    luarocks install lua-cjson

COPY scripts/remote scripts/remote

ENTRYPOINT ["/bin/ash", "scripts/remote/wrk-client.sh"]

