FROM hseeberger/scala-sbt:8u181_2.12.8_1.2.8
WORKDIR /app
COPY project project
COPY src src
COPY build.sbt build.sbt
COPY data data
COPY ssm-scripts ssm-scripts
RUN sbt -batch clean compile stage
CMD ["target/universal/stage/bin/backend", "-J-server", "-J-Xms2g", "-J-Xmx2g", "-J-XX:NewSize=1g", "-J-XX:MaxNewSize=1g", "-J-XX:InitialCodeCacheSize=256m", "-J-XX:ReservedCodeCacheSize=256m", "-J-XX:+UseParallelGC", "-J-XX:-UseBiasedLocking", "-J-XX:+AlwaysPreTouch"]
